{
    'name': 'Window & Door Product Configurator — m² Quotation',
    'version': '19.0.1.2.0',
    'category': 'Sales/Sales',
    'summary': 'For window and door manufacturers: enter dimensions, pick options, get the price instantly in Odoo Sales.',
    'description': 'static/description/index.html',
    'author': 'expodo.fr',
    'website': 'https://expodo.fr',
    'support': 'info@expodo.fr',
    'license': 'LGPL-3',
    'depends': ['sale_management'],
    'data': [
        'security/ir.model.access.csv',
        'views/cpq_product_views.xml',
        'views/cpq_configuration_views.xml',
        'views/cpq_configurator_views.xml',
        'views/cpq_line_selector_views.xml',
        'views/sale_order_views.xml',
        'views/menu.xml',
        'report/sale_report_inherit.xml',
    ],
    'demo': [
        'demo/demo_data.xml',
        'demo/demo_products_ext.xml',
    ],
    'images': ['static/description/banner.png', 'static/description/icon.png'],
    'installable': True,
    'application': True,
}
